[project]
name = "ramen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "MIT"
authors = [
    { name = "ProgCat", email = "progcat@protonmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "uv>=0.5.4",
]

[project.scripts]
ramen = "ramen.app:entrypoint"

[tool.uv.sources]
ramen-topping-torch = { workspace = true }
ramen-topping-numpy = { workspace = true }
ramen-topping-pandas = { workspace = true }
ramen-topping-plots = { workspace = true }

[tool.uv.workspace]
members = ["toppings/*"]

[dependency-groups]
dev = [
    "rust-just>=1.36.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
artifacts = [
    "artifacts/**/*"
]

[tool.hatch.build.force-include]
"./artifacts" = "artifacts"

[tool.hatch.build.targets.sdist]
exclude = ["node_modules", "dist"]

