[project]
name = "ramen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "MIT"
authors = [
    { name = "ProgCat", email = "progcat@protonmail.com" }
]
requires-python = ">=3.12"
dependencies = [
]

[project.scripts]
ramen = "ramen:entrypoint"

[tool.uv.sources]
ramen-core = { workspace = true }
ramen-cli = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
exclude = ["packages/ramen-web"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "rust-just>=1.36.0",
]

[tool.hatch.build.targets.wheel]
artifacts = [
    "artifacts/**/*"
]

[tool.hatch.build.force-include]
"./artifacts" = "artifacts"

[tool.hatch.build.targets.sdist]
exclude = ["node_modules", "dist"]

