[project]
name = "ramen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "MIT"
authors = [
    { name = "ProgCat", email = "progcat@protonmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ramen-web"
]

[project.scripts]
ramen = "ramen:entrypoint"

[tool.uv.sources]
ramen-core = { workspace = true }
ramen-cli = { workspace = true }
ramen-web = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.hatch.build.targets.wheel]
packages = ["src/ramen"]

[build-system]
requires = ["hatchling", "hatch-build-scripts"]
build-backend = "hatchling.build"

[[tool.hatch.build.targets.wheel.hooks.build-scripts.scripts]]
work_dir = "packages/ramen-web"
commands = [ "bun install", "bun run build" ]
artifacts = ["packages/ramen-web/dist"]

[tool.hatch.build.targets.sdist]
exclude = ["node_modules", "dist"]