import { Node, Edge, Connection } from '@xyflow/react';
import { nanoid } from 'nanoid';
import { useNodeDefinitionStore } from '../stores';

/**
 * 自動插入型態轉換節點
 *
 * 當兩個不同型態的 port 連接時，自動在中間插入對應的轉換節點
 *
 * @param connection 原始連線
 * @param converterType 轉換節點類型 (e.g., "type.to_string")
 * @param sourceNode 來源節點
 * @param targetNode 目標節點
 * @param setNodes 更新節點的函數
 * @param setEdges 更新連線的函數
 */
export function insertTypeConverterNode(
  connection: Connection,
  converterType: string,
  sourceNode: Node,
  targetNode: Node,
  setNodes: (updater: (nodes: Node[]) => Node[]) => void,
  setEdges: (updater: (edges: Edge[]) => Edge[]) => void
) {
  const { getNodeDefinition } = useNodeDefinitionStore.getState();
  const converterDef = getNodeDefinition(converterType);

  if (!converterDef) {
    console.error(`❌ Converter definition not found: ${converterType}`);
    return;
  }

  // 計算轉換節點位置 (兩節點中間)
  const converterPosition = {
    x: (sourceNode.position.x + targetNode.position.x) / 2,
    y: (sourceNode.position.y + targetNode.position.y) / 2 - 50  // 稍微往上偏移
  };

  // 建立轉換節點
  const converterId = `converter-${nanoid()}`;
  const converterNode: Node = {
    id: converterId,
    type: 'toType',  // 使用新的 ToType 視覺樣式
    position: converterPosition,
    data: {
      name: converterDef.displayName,
      namespace: converterDef.namespace,
      brief: converterDef.description,
      color: converterDef.color || '#795548',
      inputs: converterDef.inputs,
      outputs: converterDef.outputs,
      autoGenerated: true  // 標記為自動生成
    }
  };

  // 建立兩條連線
  const edge1: Edge = {
    id: `edge-${nanoid()}`,
    source: connection.source!,
    sourceHandle: connection.sourceHandle!,
    target: converterId,
    targetHandle: 'input0'
  };

  const edge2: Edge = {
    id: `edge-${nanoid()}`,
    source: converterId,
    sourceHandle: 'output0',
    target: connection.target!,
    targetHandle: connection.targetHandle!
  };

  console.log(`🔄 Auto-inserting type converter: ${converterType}`);
  console.log(`   ${connection.source} -> ${converterId} -> ${connection.target}`);

  // 更新狀態
  setNodes((nds) => [...nds, converterNode]);
  setEdges((eds) => [...eds, edge1, edge2]);
}
